### ISSUE TITLE
Side nav scrolling issue in Firefox

### ISSUE THREAD

**Issue by gavphillips** [StartBootstrap/pro-feedback#17]
Hi,
I've noticed on your demo site that the side nav isn't scrollable in Firefox when you have a large sub-menu open.  To see what I mean go to this page: https://themes.startbootstrap.com/sb-admin-pro/index.html and open the Components sub-menu. With this open the nav area is larger that the viewable area but I am unable to scroll down within the navigation area.  It all works perfectly in Chrome.

Thanks

**Comment by davidtmiller** [comment]
It seems that the side nav scrolling functionality is working in Firefox. It's possible that an older version of Firefox may not be supporting the scroll behavior.


https://user-images.githubusercontent.com/8400627/107994852-751f2c00-6fab-11eb-9647-3acd9fbf121a.mov
