### ISSUE TITLE
No package.json 

### ISSUE THREAD

**Issue by arcrowe** [StartBootstrap/pro-feedback#19]
There was no package.json included in the download for the PRO version

**Comment by initplatform** [comment]
Hello. 

If you have purchased a `Freelancer` license, then there is no source code included, only the final build, and therefore no need for a package.json

All other licenses come with source, which includes a package.json.

https://startbootstrap.com/licenses

The `Freelancer` license was designed for developer who only want to tweak the theme slightly, and do not want to deal with scss, pug, and a build process. 

All the best!
