### ISSUE TITLE
Bootstrap 4.6.0

### ISSUE THREAD

**Issue by agriffard** [StartBootstrap/pro-feedback#21]
Do you plan to update to Bootstrap 4.6.0 soon?

Thank you for your work.

**Comment by davidtmiller** [comment]
Hi there,

We are currently working on a new product, after which we will be coming back around to update our existing products with the 4.6.0 version of Bootstrap as well as the v5 beta!

**Comment by davidtmiller** [comment]
The new v2 release now includes Bootstrap 5. Closing this now! Thanks!
