### ISSUE TITLE
Change Port to 8000 #SB Admin Pro

### ISSUE THREAD

**Issue by diloreto** [StartBootstrap/pro-feedback#22]
Need to understand where to change the server port in the SB Admin Pro application. Thanks!

**Comment by initplatform** [comment]
Hello. You can change the development port by exporting it on the command line before `npm start`

`export PORT=4205 && npm start`

<https://docs.startbootstrap.com/sb-admin-pro-angular/quickstart#install-dependencies-and-run>

You can also change it in `scripts/start.js`
