### ISSUE TITLE
Update to Bootstrap version 5.0.2

### ISSUE THREAD

**Issue by innovaweb-dev** [StartBootstrap/pro-feedback#34]
We need that SBAdmin Pro to be updated to Bootstrap 5.0.2
The free version of SBAdmin was updated with Bootstrap 5.0.2 3 days ago, normally the PRO version must be priority.

**Comment by davidtmiller** [comment]
The pro content takes a bit longer to build and publish, but we will be pushing the release with Bootstrap 5.0.2 next week. In the meantime, if you want to update it on your own, there are not going to be any changes with the HTML with this release, so you can update to Bootstrap 5.0.2 in your `package.json` file and run `npm install` if you are using the developer version of our product. Thanks!
