### ISSUE TITLE
Where are changelog ?

### ISSUE THREAD

**Issue by innovaweb-dev** [StartBootstrap/pro-feedback#40]
Hello since version 2, the page changelog is not updated.
https://docs.startbootstrap.com/sb-admin-pro/changelog

**Comment by initplatform** [comment]
Hello,

We are giving some love to the docs currently and the changelog will be updated there. 

We don't rev the docs as frequently so the changelog may be a little behind from time to time. 

The latest changelog is also always available with the download.

https://startbootstrap.com/account/downloads
