### ISSUE TITLE
I bought SB Admin Pro however my download is Material Admin Pro

### ISSUE THREAD

**Issue by mviniciosbarreto** [StartBootstrap/pro-feedback#45]
Hi,

I bought **SB Admin Pro** however you gave me a download for **Material Admin Pro** how can I get the correct product? Here is my invoice details: f6c40082-*******

Thanks.

**Comment by initplatform** [comment]
Hi Marcos,

It looks like from your order number that you did purchase Material Admin Pro. 

Moving the conversation to email. You should have an email now from SB Support.

**Comment by mviniciosbarreto** [comment]
Replying to:

Would you like me to switch your order toes SB Admin Pro?


Please, if you can I would be very grateful. Thanks.

Em sex., 8 de abr. de 2022 às 16:52, Marcos Vinicius ***@***.***>
escreveu:

**Comment by mviniciosbarreto** [comment]
Hi Thank you for your email. Is it possible to get a copy of the SB Admin
Pro and cancel the license for Material Admin Pro? Please, let me know.
Thanks.

Em sex., 8 de abr. de 2022 às 16:48, initplatform ***@***.***>
escreveu:
