### ISSUE TITLE
Wizard Previous and Next buttons not working

### ISSUE THREAD

**Issue by mrmoriarity** [StartBootstrap/pro-feedback#56]
I have noticed the previous and next buttons are not working (demo or production code). I believe the intent should be to step through the tabs.

**Comment by davidtmiller** [comment]
This is up to the user to wire up based on how they want to use the wizard. The tabs on the top are default Bootstrap, but the buttons are just examples of what could be in the wizard. We use the tabs component with the built-in JS behavior which you can read more about here: https://getbootstrap.com/docs/5.3/components/navs-tabs/#javascript-behavior
