### ISSUE TITLE
Database connection 

### ISSUE THREAD

**Issue by carlos-alfaro** [StartBootstrap/pro-feedback#57]
Hello, we have recently buy the theme, we want to connect our MySql database but we can't find where to put the procedures to start with the validation process from the database and we can't find where is located the organisation and how to validate only registered users can open the dashboard we are trying to migrate our old platform to the new one and have on hand the java scripts to connect and validate, we used cookies to validate a user can't access the profile without validate but in the theme we download we can't find where is the order stablished

**Comment by GertJanFrl** [comment]
Hello Carlos,

The theme is only a structured design framework, depending on the version you bought. But does not contain any code for like a database connection. You have to build or add your on system for any of that to work.

**Comment by carlos-alfaro** [comment]
Hello, yes, we know is only the design framework, our old website is https://www.tupaquetico.co.cr we used bootstrap too but we have never used pug, we used handlebars to manage the things and are a little confused with the manage of the things, we bought Material Admin Pro Developer license and we think maybe you can guide us on where we can set the order of the procedures etc

 

 

Thanks and regards.. 

 

Carlos Alfaro. 
Teléfono:4001-3322  Cel 6127-3322

https://www.alsistemas.co.cr 
  
  
            

 

De: Gert-Jan Anema ***@***.***>
Responder a: StartBootstrap/pro-feedback ***@***.***>
Fecha: lunes, 26 de diciembre de 2022, 12:27
Para: StartBootstrap/pro-feedback ***@***.***>
CC: Carlos Alfaro ***@***.***>, Author ***@***.***>
Asunto: Re: [StartBootstrap/pro-feedback] Database connection (Issue #57)

 

Hello Carlos,

The theme is only a structured design framework, depending on the version you bought. But does not contain any code for like a database connection. You have to build or add your on system for any of that to work.

**Comment by davidtmiller** [comment]
Database integration with these themes are up to the user, and we do not provide support with integrations unfortunately. You could compile the HTML and bring that into your framework of choice if you don't wish to use Pug, which would be a good workaround that offers a little less flexibility, but still gives you all the core features of the theme!
