### ISSUE TITLE
SB Admin Pro - CSS styles failure in Tables.

### ISSUE THREAD

**Issue by gambatronic** [StartBootstrap/pro-feedback#58]
Hi all,

I've detected an issue related to the Table styles in 'sb-admin-pro' Admin theme,

I think it's related to the latest version of simple-datatables module.

![table styles error](https://user-images.githubusercontent.com/122461222/211832038-f7093b2b-b86b-4c13-8270-7733d6608c6a.jpg)

On the other hand, It works correctly when replacing the css "simple-datatables" request from latest to 5.0.0 version:

https://cdn.jsdelivr.net/npm/simple-datatables@5.0.0/dist/style.css

**Comment by ETIadmin** [comment]
I'm facing the same issue.However, for me it's intermittent. It seems to work fine, and after a few reloads it stops all of a sudden. After waiting for 5 min (or so), it starts working again. I'll give the 5.0 version a try until this one is fixed.

**Comment by Alessandro2408** [comment]
Today I have the same problem

**Comment by fromhope** [comment]
I have the same problem. And the '&' of the address going to the external link in the row button is marked as '&amp;', so the GET method does not work normally. 
It works NOT correctly when replacing the css "simple-datatables" request from latest to 5.0.0 version.

**Comment by ETIadmin** [comment]
> It works NOT correctly when replacing the css "simple-datatables" request from latest to 5.0.0 version.

At first it did not work for me either, until I realized that I only changed the stylesheet in the <HEAD> section, but not the <script src...> at the end of the page. So this works for me:

`<script src="https://cdn.jsdelivr.net/npm/simple-datatables@5.0.0" crossorigin="anonymous"></script>`
```
<HEAD>
   <link href="https://cdn.jsdelivr.net/npm/simple-datatables@5.0.0/dist/style.css" rel="stylesheet" />
</HEAD>
```

@gambatronic : thanks for the workaround btw.

**Comment by gambatronic** [comment]
@ETIadmin Yes,  modifying the 'simple-datatables' version in both code that you indicated it should work.

 I've been working with version 5.0.0 for a week and it works correctly for me.

**Comment by fromhope** [comment]
> > It works NOT correctly when replacing the css "simple-datatables" request from latest to 5.0.0 version.
> 
> At first it did not work for me either, until I realized that I only changed the stylesheet in the section, but not the <script src...> at the end of the page. So this works for me:
> 
> `<script src="https://cdn.jsdelivr.net/npm/simple-datatables@5.0.0" crossorigin="anonymous"></script>`
> 
> ```
> <HEAD>
>    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@5.0.0/dist/style.css" rel="stylesheet" />
> </HEAD>
> ```
> 
> @gambatronic : thanks for the workaround btw.

Thanks for your response.

I can see the design of the table well, but the '&' symbols brought from the address bar to the GET variable are all changed to '@amp;', resulting in an error. Other pages don't get an error where the '&' sign is changed, but only this table is getting an error.

**Comment by davidtmiller** [comment]
We did fix this up in the last release, so I am going to mark this one as closed. To fix this up you can download the updated theme from your Start Bootstrap dashboard and use the new CSS styles to fix this up!
