### ISSUE TITLE
DataTables in mobile view

### ISSUE THREAD

**Issue by indev-at** [StartBootstrap/pro-feedback#60]
![image](https://user-images.githubusercontent.com/74143069/214290960-8ef75d74-781c-48d0-a55d-d7b799990cbe.png)

Datatables overflow out of the card.

Maybe this could be included in the next bugfix ;)

a quick solution would be:

```
.datatable-container {
    overflow-x: scroll;
}
```

![image](https://user-images.githubusercontent.com/74143069/214291665-17b10aa4-ef1d-4637-95e0-54f67d999f84.png)

**Comment by davidtmiller** [comment]
We did fix this up with the last update, so I will mark this as closed.
