### ISSUE TITLE
Contain everything within a .container

### ISSUE THREAD

**Issue by sumpfgottheit** [StartBootstrap/pro-feedback#62]
Hi,

I would like to have the whole page within a .container, including top nav and the sidebar. I have only found examples how to use .container or .container-fluid with the content, but not the whole page.

Is there and example or can anyone provide me guidance, how I can achive this?

**Comment by davidtmiller** [comment]
Hi there, with the SB Admin pro theme, putting everything in a container including the sidebar isn't supported. What we show in the preview, the fixed and scrollable sidebar, along with the fluid and container content sections, are what are included with the theme.

This is a feature that the user would need to develop on their own past the base functionality of the theme.
