### ISSUE TITLE
Side nav not rendering correctly

### ISSUE THREAD

**Issue by askew** [StartBootstrap/pro-feedback#64]
When I download the sb-admin-pro theme (version 2.0.5) and run `npm install`, `npm run start` this is what it looks like:

![image](https://github.com/StartBootstrap/pro-feedback/assets/2727893/82d490b1-90a2-4f93-a4e8-1134e6d0c7a4)

Why is the left nav not correct?

**Comment by davidtmiller** [comment]
It appears the CSS is not loading properly in your project. I would try running through the install again and checking to make sure that the CSS is building. This appears to be a user-end bug and not a bug with the theme, so I will close this, but feel free to comment to see if we can get this solved for you.
