### ISSUE TITLE
Button colors

### ISSUE THREAD

**Issue by BrokerT** [StartBootstrap/pro-feedback#66]
I'm using the SB UI Kit Pro and I was trying to make my button colors to gray in the navbar where you have them "teal", yet when I use "gray" they just disappear. 
What am I doing wrong?
Another issue: I made changes to my Navbar and have gone thru saving it and it updated on a few pages but some pages still have old menu item and navbar links in the drop down menus. Am I missing something or is there multiple navbars? I only see the one navbar mixin.

One other question is it possible to mix the two packages together? If so is there documentation on how to structure that? I bought the Bundle of UI Kit Pro and the SB Admin package.
Thanks,
Tony

**Comment by BrokerT** [comment]
The Navbar issue corrected itself the next time I logged in and reran the start command.

**Comment by davidtmiller** [comment]
Looks like this got resolved, so I will mark this as closed for now!
