### ISSUE TITLE
Utility Animation not working in Edge

### ISSUE THREAD

**Issue by developeregrem** [StartBootstrap/pro-feedback#7]
Hi,
first of all you did a great job with the UI Kit Pro. I really like it.

I figured out, that the animation classes did not work in latest Edge Browser. You can see it in your example page her: https://themes.startbootstrap.com/sb-ui-kit-pro/index.html in the nav dropdown.
The dropdown content is not shown when clicking on the link.
When removing the css class animated--fade-in-up it's working.

**Comment by davidtmiller** [comment]
We will do some more testing in Edge. It looks like this might be an issue with autoprefixer not compiling some cross browser functionality rules and selectors into the CSS.

**Comment by davidtmiller** [comment]
Looking into this for our v1.2.1 release of SB UI Kit Pro and SB Admin Pro.

**Comment by davidtmiller** [comment]
Animation utilities are now working as intended in v2 on Edge v90.0.818.62. Closing this one!
